# TUGAS 4
**Nama  : Zahrah Mahfuzah    
NPM   : 2106704004   
Kelas : A (bu bev)**

# Soal Nomor 1

In [52]:
import numpy as np # memasukkan modul

pada cell di atas, modul numpy dimasukkan agar program di bawah dapat dijalankan

In [53]:
def BackSubstitution(matrix): # pendefinisian fungsi Back Substitution
    n = np.shape(matrix)[0]
    solution = np.zeros(n)
    solution[n-1] = matrix[n-1, n]/matrix[n-1, n-1]
    for i in range (n-2, -1, -1):
        for j in range(i+1, n): # banyak persamaan
            matrix[i,n] -= matrix[i,j]*solution[j] # array untuk menyimpan solusi
        solution[i] = matrix[i,n]/matrix[i,i] # subtitusi balik dimulai
    return solution

def PartialPivoting(matrix): # pendefinisian fungsi Partial Pivoting
    n = np.shape(matrix)[0] # mengambil ukuran baris dari matriks
    for i in range(n-1):
        below_pivot = abs(matrix[i:,i])
        pivot_row = np.argmax(below_pivot) # mengambil elemen maksimum   
        if matrix[i,pivot_row+i] == 0: # jika baris yang akan dipivot nol, maka program akan mencetak bahwa matriks tidak memiliki solusi unik
            return "Tidak ada solusi unik"
        else:
            matrix[[pivot_row+i,i]]= matrix[[i,pivot_row+i]] # pertukaran baris    
            
        for j in range(i+1,n):
            m = matrix[j,i]/matrix[i,i]
            matrix[j] = matrix[j]-m*matrix[i]
            print(matrix)     
    return matrix

def ScaledPartialPivoting(matrix): # pendefinisian fungsi Scaled Partial Pivoting
    n = np.shape(matrix)[0] # mengambil ukuran baris dari matriks
    s = np.array([max(abs(matrix[i,:n])) for i in range(n)]) # menentukan scalar tiap kolom dibandingkan masing2 baris yang paling besar 
    if 0 in s: # SPL tidak memiliki solusi karena ada baris yang hanya berisi 0
        return "Tidak ada solusi unik"  
    for i in range(n-1):
        below_pivot = abs(matrix[i:,i])/s[i:]
        pivot_row = np.argmax(below_pivot)
        if matrix[i,pivot_row+i] == 0:
            return "Tidak ada solusi unik"
        else:
            matrix[[pivot_row+i,i]] = matrix[[i,pivot_row+i]]
            s[pivot_row+i],s[i]=s[i],s[pivot_row+i]    
        for j in range(i+1,n): # eliminasi gauss
            m = matrix[j,i]/matrix[i,i]
            matrix[j] = matrix[j]-m*matrix[i]
            print(matrix)
    return matrix

Pada cell di atas, didefinisikan fungsi Back Substitution, Partial Pivoting, dan Scaled Partial Pivoting yang nantinya akan digunakan pada program di bawah.

In [54]:
run = "yes"
while run == "yes": # fungsi loop selama run = yes
    NPM = str(input("Masukkan NPM anda : ")) # meminta input npm
    
    matrix = [] # membuat inisiasi list kosong untuk matrix
    b1 = [] # inisiasi list kosong untuk baris pertama
    b2 = [] # inisiasi list kosong untuk baris kedua
    b3 = [] # inisiasi list kosong untuk baris ketiga
    b4 = [] # inisiasi list kosong untuk baris keempat
    
    for i in range (0,5,1): 
        isi1 = np.random.randint(-100,100) # mengambil 5 bil random 100<=x<100
        b1.append(isi1)
        isi2 = int(NPM[i]) # mengambil 5 digit awal npm
        b2.append(isi2)
        isi4 = np.random.randint(-100,100) # mengambil 5 bil random 100<=x<100
        b4.append(isi4)
        
    for j in range (5,10,1):
        isi3 = int(NPM[j]) # mengambil digit 6-10 npm
        b3.append(isi3)
        
    
    matrix.append(b1)
    matrix.append(b2)
    matrix.append(b3)
    matrix.append(b4)
    
    print(matrix) # mencetak matrix
    
    print("Berikut adalah augmented matrix yang terbentuk.")
    matrix_array = np.array(matrix) # menjadikan matrix ke dalam bentuk array
    print(matrix_array)
    
    
    print("\n ========== PARTIAL PIVOTING ========== ")
    triangular_form = PartialPivoting(matrix_array)
    solution = BackSubstitution(triangular_form)
    print("Tringular matriksnya adalah \n{0}".format(triangular_form))
    print("Solusi SPL \n{0}".format(solution))
    
    
    print("\n ========== SCALED PARTIAL PIVOTING ==========")
    triangular_form2 = ScaledPartialPivoting(matrix_array)
    solution2 = BackSubstitution(triangular_form2)
    print("Triangular matriksnya adalah \n{0}".format(triangular_form2))
    print("Solusi SPL \n{0}".format(solution2))
    
    run = input("Mengulang program? ") # input yes or no untuk menentukan fungsi loop berjalan kembali atau berhenti
    if run == "yes": 
        continue # fungsi loop lanjut jalan
    elif run == "no":
        print("Dadah")
        break # fungsi loop berhenti
    else:
        print("Input tidak sesuai. Program dihentikan.")
        break # fungsi loop berhenti
        

Masukkan NPM anda : 2106704004
[[47, 24, -13, 72, -4], [2, 1, 0, 6, 7], [0, 4, 0, 0, 4], [27, -37, 48, 69, -22]]
Berikut adalah augmented matrix yang terbentuk.
[[ 47  24 -13  72  -4]
 [  2   1   0   6   7]
 [  0   4   0   0   4]
 [ 27 -37  48  69 -22]]

 ========== PARTIAL PIVOTING ========== 
[[ 47  24 -13  72  -4]
 [  0   0   0   2   7]
 [  0   4   0   0   4]
 [ 27 -37  48  69 -22]]
[[ 47  24 -13  72  -4]
 [  0   0   0   2   7]
 [  0   4   0   0   4]
 [ 27 -37  48  69 -22]]
[[ 47  24 -13  72  -4]
 [  0   0   0   2   7]
 [  0   4   0   0   4]
 [  0 -50  55  27 -19]]
[[ 47  24 -13  72  -4]
 [  0 -50  55  27 -19]
 [  0   0   4   2   2]
 [  0   0   0   2   7]]
[[ 47  24 -13  72  -4]
 [  0 -50  55  27 -19]
 [  0   0   4   2   2]
 [  0   0   0   2   7]]
[[ 47  24 -13  72  -4]
 [  0 -50  55  27 -19]
 [  0   0   4   2   2]
 [  0   0   0   2   7]]
Tringular matriksnya adalah 
[[  47   24  -13   72 -293]
 [   0  -50   55   27  -45]
 [   0    0    4    2   -5]
 [   0    0    0    2    7]]
Solu

Pada program di atas, dijalankan fungsi pemograman untuk mencari solusi unik dari matriks.

Pertama, program akan meminta input NPM dan menggunakan digit 1-5 sebagai baris kedua matriks dan digit 6-10 sebagai baris ketiga matriks. Baris pertama dan keempat akan dilengkapi dengan mengambil angka random berupa bilangan bulat yang kurang dari 100.

Program akan mencetak augmented matriks yang akan digunakan dan menjalankan program sesuai dengan definisi fungsi yang telah diberikan. Kemudian, program akan mencetak hasil dari tringular matriks dan solusi SPLnya.

Setelah itu akan ditanyakan apakah program akan dijalankan kembali atau tidak. Jika user memasukkan input "yes", maka program akan berjalan kembali. Jika user memasukkan input "no", maka program akan keluar dari fungsi while dan berhenti. Jika user memasukkan input selain "yes" dan "no", maka program akan keluar dari fungsi while dan berhenti secara paksa.

# Soal Nomor 2

In [2]:
import numpy as np

pada cell di atas, modul numpy dimasukkan agar program di bawah dapat dijalankan

In [3]:
def LUFactorization(matrix): # pendefinisian fungsi LU Factorization
    n = np.shape(matrix)[0]  # mengambil ukuran baris dari matriks
    L = np.identity(n) # mendefinisikan L sebagai matriks identitas nxn
    # operasi baris elementer
    for i in range(n):
        for j in range(i+1, n):
            m = matrix[j,i]/matrix[i,i]
            L[j,i] = m # pasang elemen L_ji menjadi multiplisitas m = a_ji/a_ii
            matrix[j] = matrix[j]-m*matrix[i]    
    return (L, matrix)

Pada cell di atas, didefinisikan fungsi LU Factorization yang nantinya akan digunakan pada program di bawah.

In [4]:
matrix = eval(input("Masukkan matriks anda A : ")) # meminta input matrix
A = np.array(matrix)

z = 0
for z in range (10):
    print("=========================")
    L = LUFactorization(A)[0] # mengambil L pada LU Factorization
    U = LUFactorization(A)[1] # mengambil matriks pada LU Factorization
    a = np.round(L) # membulatkan nilai L
    b = np.round(U) # membulatkan nilai U
    print("Matriks L \n", a) 
    print("Matriks U \n", b)
    
    Az = a + b
    print("Matriks A{0} \n{1}".format(z+1, Az))
    A = Az


Masukkan matriks anda A :  [[7,3,6],[1,5,2],[6,2,7]]


Matriks L 
 [[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 1.]]
Matriks U 
 [[7 3 6]
 [0 4 1]
 [0 0 1]]
Matriks A1 
[[8. 3. 6.]
 [0. 5. 1.]
 [1. 0. 2.]]
Matriks L 
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
Matriks U 
 [[8. 3. 6.]
 [0. 5. 1.]
 [0. 0. 1.]]
Matriks A2 
[[9. 3. 6.]
 [0. 6. 1.]
 [0. 0. 2.]]
Matriks L 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriks U 
 [[9. 3. 6.]
 [0. 6. 1.]
 [0. 0. 2.]]
Matriks A3 
[[10.  3.  6.]
 [ 0.  7.  1.]
 [ 0.  0.  3.]]
Matriks L 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriks U 
 [[10.  3.  6.]
 [ 0.  7.  1.]
 [ 0.  0.  3.]]
Matriks A4 
[[11.  3.  6.]
 [ 0.  8.  1.]
 [ 0.  0.  4.]]
Matriks L 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriks U 
 [[11.  3.  6.]
 [ 0.  8.  1.]
 [ 0.  0.  4.]]
Matriks A5 
[[12.  3.  6.]
 [ 0.  9.  1.]
 [ 0.  0.  5.]]
Matriks L 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matriks U 
 [[12.  3.  6.]
 [ 0.  9.  1.]
 [ 0.  0.  5.]]
Matriks A6 
[[13.  3.  6.]
 [ 0. 10.  1.]
 [ 0.  0.  6.]]
Matriks L 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Matrik

Pada program di atas, dijalankan fungsi pemograman untuk mencari hasil LU Factorization dari matriks.

Pertama, program akan meminta input matriks yang akan digunakan dalam proses LU Factorization.

Kemudian, program akan berjalan berdasarkan fungsi yang didefinisikan dan mencetak matriks L, matriks U, dan matriks Az selama z<10. Setelah z=10, program akan berhenti dan mencetak A10 sebagai hasil akhir dari proses LU Factorization.