# TUGAS 5
**Nama  : Zahrah Mahfuzah    
NPM   : 2106704004    
Kelas : A (bu bev)**

# Soal Nomor 1A

In [40]:
import numpy as np #memasukkan modul
from tabulate import tabulate

pada cell di atas, modul numpy dimasukkan agar program di bawah dapat dijalankan

In [41]:
def Jacobi(matrix,initial,tol): #mendefinisikan fungsi Jacobi
    n = np.shape(matrix)[0] #ukuran matrix/banyak variabel
    x0 = initial #mendefinisikan x0 sebagai tebakan awal
    x = x0.copy() #mendefinisikan x = x0 
    
    for i in range(n):
        b = matrix[i,n] #konstanta pada SPL
        for j in range(n): #metode Jacobi
            if j!=i:
                b-=matrix[i,j]*x0[j]
        x[i]=b/matrix[i,i] #hasil aproksimasi Jacobi
    
    tab = [] #membuat list kosong
    iterasi = 1
    
    while np.linalg.norm(x-x0,np.inf)>=tol: #pengecekan kriteria penyetop menggunakan error mutlak
        x0 = x #mendefinisikan x0 sebagai x(k-1)
        x = x0.copy() #mendefinisikan x sebagai x(k), namun awalnya samakan dengan x0
        for i in range(n): #metode Jacobi
            b = matrix[i,n]
            for j in range(n):
                if j!=i:
                    b-=matrix[i,j]*x0[j]
            x[i]=b/matrix[i,i]
        
        tab.append([iterasi, x[0], x[1], x[2]])
        iterasi += 1
            
    tab.append([iterasi, x[0], x[1], x[2]]) #memasukkan nilai yang didapatkan ke dalam array
    print(tabulate(tab, headers = ["iterasi", "x1", "x2", "x3"], tablefmt = "pretty")) #mengubah ke bentuk tabel
    return x #nilai yang direturn ke fungsi ini adalah x(k)

def GaussSeidel(matrix,initial,tol):
    n = np.shape(matrix)[0] #ukuran matrix/banyak variabel
    x0 = initial #definisikan x0 sebagai tebakan awal
    x = x0.copy() #definisikan x = x0
    
    for i in range(n):
        b = matrix[i,n] #konstanta pada SPL
        for j in range(n):
            if j!=i:
                if j<i:
                    b-=matrix[i,j]*x[j]
                else:
                    b-=matrix[i,j]*x0[j]
        x[i]=b/matrix[i,i] #hasil aproksimasi gauss seidel
        
    tab = [] #membuat list kosong
    iterasi = 1
    
    while np.linalg.norm(x-x0,np.inf)>=tol: #pengecekan kriteria penyetop menggunakan error mutlak
        x0 = x #mendefinisikan x0 sebagai x(k-1)
        x = x0.copy() #mendefinisikan x sebagai x(k)
        for i in range(n): #metode gauss seidel
            b = matrix[i,n]
            for j in range(n):
                if j!=i:
                    if j<i:
                        b-=matrix[i,j]*x[j]
                    else:
                        b-=matrix[i,j]*x0[j]
            x[i]=b/matrix[i,i]
        
        tab.append([iterasi, x[0], x[1], x[2]]) 
        iterasi += 1
    
    tab.append([iterasi, x[0], x[1], x[2]]) #memasukkan nilai ke array
    print(tabulate(tab, headers = ["iterasi", "x1", "x2", "x3"], tablefmt = "pretty")) #mengubah ke bentuk tabel
    return x #nilai yang direturn ke fungsi ini adalah x(k)

Pada cell di atas, didefinisikan fungsi Jacobi dan Gauss Seidel yang nantinya akan digunakan pada program di bawah.

In [42]:
#Meminta input
aug_matrix = np.array(eval(input("Masukkan augmented matrix dari SPL yang akan diselesaikan : ")))
initial_solution = np.array(eval(input("Masukkan tebakan awal solusi : ")),dtype=float)
tolerance = eval(input("Masukkan toleransi : "))
print(aug_matrix)

print("-------------------Metode Jacobi-------------------")
print(Jacobi(aug_matrix,initial_solution,tolerance))
print("====================================================================")
print("-------------------Metode Gauss-Seidel-------------------")
print(GaussSeidel(aug_matrix,initial_solution,tolerance))

Masukkan augmented matrix dari SPL yang akan diselesaikan : [[2,-1,1,-1], [2,2,2,4],[-1,-1,2,-5]]
Masukkan tebakan awal solusi : [0,0,0]
Masukkan toleransi : 10**-5
[[ 2 -1  1 -1]
 [ 2  2  2  4]
 [-1 -1  2 -5]]
-------------------Metode Jacobi-------------------


<ipython-input-41-77834b6111c7>:23: RuntimeWarning: overflow encountered in double_scalars
  b-=matrix[i,j]*x0[j]
<ipython-input-41-77834b6111c7>:16: RuntimeWarning: invalid value encountered in subtract
  while np.linalg.norm(x-x0,np.inf)>=tol: #pengecekan kriteria penyetop menggunakan error mutlak


+---------+--------------------------+--------------------------+--------------------------+
| iterasi |            x1            |            x2            |            x3            |
+---------+--------------------------+--------------------------+--------------------------+
|    1    |           1.75           |           5.0            |          -1.75           |
|    2    |          2.875           |           2.0            |          0.875           |
|    3    |          0.0625          |          -1.75           |         -0.0625          |
|    4    |         -1.34375         |           2.0            |         -3.34375         |
|    5    |         2.171875         |          6.6875          |        -2.171875         |
|    6    |        3.9296875         |           2.0            |        1.9296875         |
|    7    |       -0.46484375        |        -3.859375         |        0.46484375        |
|    8    |       -2.662109375       |           2.0            |     

Pada program di atas, dijalankan fungsi pemograman untuk mencari solusi dari SPL dengan menggunakan metode Jacobi dan Gauss Seidel.

Pertama, program akan meminta input matriks yang akan diselesaikan, tebakan awal solusi, dan toleransi error yang akan digunakan pada metode Jacobi dan Gauss Seidel.

Kemudian, program akan berjalan sesuai dengan fungsi metode Jacobi dan Gauss Seidel yang sudah didefinisikan pada cell sebelumnya.

Program akan berhenti ketika telah memenuhi batas toleransi yang sudah ditentukan dan mencetak hasil solusi ke dalam bentuk tabel

#   1B dan 1C

**1B**
Dapat dilihat dari tabel di atas untuk metode Jacobi diperlukan sebanyak 6350 iterasi, sedangkan untuk metode Gauss Seidel dibutuhkan sebanyak 23 iterasi.

**1C**
Iya, terdapat perbedaan. Metode Jacobi membutuhkan lebih banyak iterasi daripada Metode Gauss Seidel. Selain itu, hasil aproksimasi dari Metode Jacobi adalah infinity, sedangkan pada Metode Gauss Seidel dihasilkan [ 1.00000226  1.9999975  -1.00000012]


# Soal Nomor 1D

In [43]:
import numpy as np #memasukkan modul
from tabulate import tabulate

pada cell di atas, modul numpy dimasukkan agar program di bawah dapat dijalankan

In [44]:
def Jacobi(matrix,initial,tol): #mendefinisikan fungsi Jacobi
    n = np.shape(matrix)[0] #ukuran matrix/banyak variabel
    x0 = initial #mendefinisikan x0 sebagai tebakan awal
    x = x0.copy() #mendefinisikan x = x0 
    
    for i in range(n):
        b = matrix[i,n] #konstanta pada SPL
        for j in range(n): #metode Jacobi
            if j!=i:
                b-=matrix[i,j]*x0[j]
        x[i]=b/matrix[i,i] #hasil aproksimasi Jacobi
    
    tab = [] #membuat list kosong
    iterasi = 1
    
    while np.linalg.norm(x-x0,np.inf)>=tol: #pengecekan kriteria penyetop menggunakan error mutlak
        x0 = x #mendefinisikan x0 sebagai x(k-1)
        x = x0.copy() #mendefinisikan x sebagai x(k), namun awalnya samakan dengan x0
        for i in range(n): #metode Jacobi
            b = matrix[i,n]
            for j in range(n):
                if j!=i:
                    b-=matrix[i,j]*x0[j]
            x[i]=b/matrix[i,i]
        
        tab.append([iterasi, x[0], x[1], x[2]])
        iterasi += 1
            
    tab.append([iterasi, x[0], x[1], x[2]]) #memasukkan nilai yang didapatkan ke dalam array
    print(tabulate(tab, headers = ["iterasi", "x1", "x2", "x3"], tablefmt = "pretty")) #mengubah ke bentuk tabel
    return x #nilai yang direturn ke fungsi ini adalah x(k)

def GaussSeidel(matrix,initial,tol):
    n = np.shape(matrix)[0] #ukuran matrix/banyak variabel
    x0 = initial #definisikan x0 sebagai tebakan awal
    x = x0.copy() #definisikan x = x0
    
    for i in range(n):
        b = matrix[i,n] #konstanta pada SPL
        for j in range(n):
            if j!=i:
                if j<i:
                    b-=matrix[i,j]*x[j]
                else:
                    b-=matrix[i,j]*x0[j]
        x[i]=b/matrix[i,i] #hasil aproksimasi gauss seidel
        
    tab = [] #membuat list kosong
    iterasi = 1
    
    while np.linalg.norm(x-x0,np.inf)>=tol: #pengecekan kriteria penyetop menggunakan error mutlak
        x0 = x #mendefinisikan x0 sebagai x(k-1)
        x = x0.copy() #mendefinisikan x sebagai x(k)
        for i in range(n): #metode gauss seidel
            b = matrix[i,n]
            for j in range(n):
                if j!=i:
                    if j<i:
                        b-=matrix[i,j]*x[j]
                    else:
                        b-=matrix[i,j]*x0[j]
            x[i]=b/matrix[i,i]
        
        tab.append([iterasi, x[0], x[1], x[2]]) 
        iterasi += 1
    
    tab.append([iterasi, x[0], x[1], x[2]]) #memasukkan nilai ke array
    print(tabulate(tab, headers = ["iterasi", "x1", "x2", "x3"], tablefmt = "pretty")) #mengubah ke bentuk tabel
    return x #nilai yang direturn ke fungsi ini adalah x(k)

Pada cell di atas, didefinisikan fungsi Jacobi dan Gauss Seidel yang nantinya akan digunakan pada program di bawah.

In [45]:
#Meminta input
aug_matrix = np.array(eval(input("Masukkan augmented matrix dari SPL yang akan diselesaikan : ")))
initial_solution = np.array(eval(input("Masukkan tebakan awal solusi : ")),dtype=float)
tolerance = eval(input("Masukkan toleransi : "))
print(aug_matrix)

print("-------------------Metode Jacobi-------------------")
print(Jacobi(aug_matrix,initial_solution,tolerance))
print("====================================================================")
print("-------------------Metode Gauss-Seidel-------------------")
print(GaussSeidel(aug_matrix,initial_solution,tolerance))

Masukkan augmented matrix dari SPL yang akan diselesaikan : [[2,-1,1,-1], [2,2,2,4],[-1,-1,2,-5]]
Masukkan tebakan awal solusi : [1,1,1]
Masukkan toleransi : 10**-5
[[ 2 -1  1 -1]
 [ 2  2  2  4]
 [-1 -1  2 -5]]
-------------------Metode Jacobi-------------------


<ipython-input-44-77834b6111c7>:23: RuntimeWarning: overflow encountered in double_scalars
  b-=matrix[i,j]*x0[j]
<ipython-input-44-77834b6111c7>:23: RuntimeWarning: invalid value encountered in double_scalars
  b-=matrix[i,j]*x0[j]
<ipython-input-44-77834b6111c7>:16: RuntimeWarning: invalid value encountered in subtract
  while np.linalg.norm(x-x0,np.inf)>=tol: #pengecekan kriteria penyetop menggunakan error mutlak


+---------+--------------------------+--------------------------+--------------------------+
| iterasi |            x1            |            x2            |            x3            |
+---------+--------------------------+--------------------------+--------------------------+
|    1    |           0.25           |           4.0            |          -2.75           |
|    2    |          2.875           |           4.5            |          -0.375          |
|    3    |          1.9375          |           -0.5           |          1.1875          |
|    4    |         -1.34375         |          -1.125          |         -1.78125         |
|    5    |        -0.171875         |          5.125           |        -3.734375         |
|    6    |        3.9296875         |         5.90625          |        -0.0234375        |
|    7    |        2.46484375        |         -1.90625         |        2.41796875        |
|    8    |       -2.662109375       |        -2.8828125        |     

Pada program di atas, dijalankan fungsi pemograman untuk mencari solusi dari SPL dengan menggunakan metode Jacobi dan Gauss Seidel.

Pertama, program akan meminta input matriks yang akan diselesaikan, tebakan awal solusi, dan toleransi error yang akan digunakan pada metode Jacobi dan Gauss Seidel.

Kemudian, program akan berjalan sesuai dengan fungsi metode Jacobi dan Gauss Seidel yang sudah didefinisikan pada cell sebelumnya.

Program akan berhenti ketika telah memenuhi batas toleransi yang sudah ditentukan dan mencetak hasil solusi ke dalam bentuk tabel

Dari tabel di atas, didapatkan hasil aproksimasi untuk tebakan awal = [1,1,1,1] yaitu 
- Metode Jacobi mendapatkan solusi inifinity pada iterasi ke 6353
- Metode Gauss Seidel mendapatkan solusi [0.99999744  2.0000028  -0.99999988  1.        ] pada iterasi ke 24

**Disimpulkan bahwa hasilnya tidak jauh berbeda**

# Soal Nomor 2

In [46]:
import numpy as np
from tabulate import tabulate

pada cell di atas, modul numpy dimasukkan agar program di bawah dapat dijalankan

In [47]:
def Jacobi(matrix,initial,tol): #mendefinisikan fungsi Jacobi
    n = np.shape(matrix)[0] #ukuran matrix/banyak variabel
    x0 = initial #mendefinisikan x0 sebagai tebakan awal
    x = x0.copy() #mendefinisikan x = x0 
    
    for i in range(n):
        b = matrix[i,n] #konstanta pada SPL
        for j in range(n): #metode Jacobi
            if j!=i:
                b-=matrix[i,j]*x0[j]
        x[i]=b/matrix[i,i] #hasil aproksimasi Jacobi
    
    tab = [] #membuat list kosong
    iterasi = 1
    
    while np.linalg.norm(x-x0,np.inf)>=tol and iterasi<500: #pengecekan kriteria penyetop menggunakan error mutlak
        x0 = x #mendefinisikan x0 sebagai x(k-1)
        x = x0.copy() #mendefinisikan x sebagai x(k), namun awalnya samakan dengan x0
        for i in range(n): #metode Jacobi
            b = matrix[i,n]
            for j in range(n):
                if j!=i:
                    b-=matrix[i,j]*x0[j]
            x[i]=b/matrix[i,i]
        
        tab.append([iterasi, x[0], x[1], x[2]])
        iterasi += 1
            
    tab.append([iterasi, x[0], x[1], x[2]]) #memasukkan nilai yang didapatkan ke dalam array
    print(tabulate(tab, headers = ["iterasi", "x1", "x2", "x3"], tablefmt = "pretty")) #mengubah ke bentuk tabel
    return x #nilai yang direturn ke fungsi ini adalah x(k)

def GaussSeidel(matrix,initial,tol):
    n = np.shape(matrix)[0] #ukuran matrix/banyak variabel
    x0 = initial #definisikan x0 sebagai tebakan awal
    x = x0.copy() #definisikan x = x0
    
    for i in range(n):
        b = matrix[i,n] #konstanta pada SPL
        for j in range(n):
            if j!=i:
                if j<i:
                    b-=matrix[i,j]*x[j]
                else:
                    b-=matrix[i,j]*x0[j]
        x[i]=b/matrix[i,i] #hasil aproksimasi gauss seidel
        
    tab = [] #membuat list kosong
    iterasi = 1
    
    while np.linalg.norm(x-x0,np.inf)>=tol and iterasi<500: #pengecekan kriteria penyetop menggunakan error mutlak
        x0 = x #mendefinisikan x0 sebagai x(k-1)
        x = x0.copy() #mendefinisikan x sebagai x(k)
        for i in range(n): #metode gauss seidel
            b = matrix[i,n]
            for j in range(n):
                if j!=i:
                    if j<i:
                        b-=matrix[i,j]*x[j]
                    else:
                        b-=matrix[i,j]*x0[j]
            x[i]=b/matrix[i,i]
        
        tab.append([iterasi, x[0], x[1], x[2]]) 
        iterasi += 1
    
    tab.append([iterasi, x[0], x[1], x[2]]) #memasukkan nilai ke array
    print(tabulate(tab, headers = ["iterasi", "x1", "x2", "x3"], tablefmt = "pretty")) #mengubah ke bentuk tabel
    return x #nilai yang direturn ke fungsi ini adalah x(k)

Pada cell di atas, didefinisikan fungsi Jacobi dan Gauss Seidel yang nantinya akan digunakan pada program di bawah.

In [48]:
#Meminta input
aug_matrix = np.array(eval(input("Masukkan augmented matrix dari SPL yang akan diselesaikan : ")))
initial_solution = np.array(eval(input("Masukkan tebakan awal solusi : ")),dtype=float)
tolerance = eval(input("Masukkan toleransi : "))
print(aug_matrix)

print("-------------------Metode Jacobi-------------------")
print(Jacobi(aug_matrix,initial_solution,tolerance))
print("====================================================================")
print("-------------------Metode Gauss-Seidel-------------------")
print(GaussSeidel(aug_matrix,initial_solution,tolerance))

Masukkan augmented matrix dari SPL yang akan diselesaikan : [[1,4,1,2,8],[1,4,1,1,7],[1,2,3,2,8],[1,1,7,4,14]]
Masukkan tebakan awal solusi : [1,1,1,1]
Masukkan toleransi : 10**-4
[[ 1  4  1  2  8]
 [ 1  4  1  1  7]
 [ 1  2  3  2  8]
 [ 1  1  7  4 14]]
-------------------Metode Jacobi-------------------
+---------+--------------------------+--------------------------+--------------------------+
| iterasi |            x1            |            x2            |            x3            |
+---------+--------------------------+--------------------------+--------------------------+
|    1    |           0.5            |          0.9375          |    0.8333333333333334    |
|    2    |    0.9166666666666665    |    1.1041666666666667    |    1.0416666666666667    |
|    3    |    -0.822916666666667    |    0.8398437500000001    |    0.5034722222222223    |
|    4    |    1.7934027777777772    |    1.5368923611111112    |    1.5998263888888893    |
|    5    |    -4.976779513888889    |   0.2

Pada program di atas, dijalankan fungsi pemograman untuk mencari solusi dari SPL dengan menggunakan metode Jacobi dan Gauss Seidel.

Pertama, program akan meminta input matriks yang akan diselesaikan, tebakan awal solusi, dan toleransi error yang akan digunakan pada metode Jacobi dan Gauss Seidel.

Kemudian, program akan berjalan sesuai dengan fungsi metode Jacobi dan Gauss Seidel yang sudah didefinisikan pada cell sebelumnya.

Program akan berhenti ketika telah memenuhi batas toleransi atau ketika iterasi mencapai 500. Hal ini dilakukan agar program tidak mengalami error karena overflowing.

Dari tabel di atas, didapatkan hasil aproksimasi untuk tebakan awal = [1,1,1,1] yaitu 
- Metode Jacobi mendapatkan solusi [-2.13177400e+161 -4.56602856e+160 -7.79753276e+160 -9.51178623e+160] pada iterasi ke 500
- Metode Gauss Seidel mendapatkan solusi [-510374.54488303  100391.47919489   -4793.6246963   110888.10964056] pada iterasi ke 500

**Disimpulkan bahwa hasil keduanya divergen dan hasil aproksimasi metode Gauss-Seidel lebih baik karena hasilnya tidak sebesar Jacobi**